export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const GET_MEASUREMENTS_DATA_RECEIVED = "EVENT/GET_MEASUREMENTS_DATA_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
