export const API_ERROR = 'EVENT/API_ERROR_RECEIVED';
export const GET_METRICS_DATA_RECEIVED = 'EVENT/GET_METRICS_DATA_RECEIVED';
export const GET_MEASUREMENTS_DATA_RECEIVED =
  'EVENT/GET_MEASUREMENTS_DATA_RECEIVED';
export const GET_MULTIPLE_MEASUREMENTS_DATA_RECEIVED =
  'EVENT/GET_MULTIPLE_MEASUREMENTS_DATA_RECEIVED';
export const SET_SELECTED_METRICS = 'EVENT/SET_SELECTED_METRICS';
export const SUBSCRIPTION_NEW_MEASUREMENT_RECEIVED =
  'EVENT/SUBSCRIPTION_NEW_MEASUREMENT_RECEIVED';
export const WEATHER_DATA_RECEIVED = 'EVENT/WEATHER_DATA_RECEIVED';
